- name: Ensure .kube directory exists.
  file:
    path: ~/.kube
    state: directory
    mode: 0755
  when: "'k8s-master' in group_names"

- name: Copy the kubectl admin.conf to ~/.kube/conf
  file:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config
    state: link
    mode: 0644
  when: "'k8s-master' in group_names"

- name: Ensure kubectl alias exists
  lineinfile:
    path: ~/.bashrc
    line: "{{ item }}"
  with_items:
    - ""
    - "### k8s setting by ansible"
    - "alias k=kubectl"
    - ""
  when: "'k8s-master' in group_names"